# Generated by Django 5.2.6 on 2025-10-01 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', 'date'], name='appointment_user_id_7093d3_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date', 'time'], name='appointment_date_397cae_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'time'), name='uniq_user_date_time'),
        ),
    ]
